version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "LayerName=\"RhubarbLambdaLayer\" PythonPackages=\"pyrhubarb==0.0.3\""
image_repositories = []
