Name: deployment
SchemaVersion: '1.0'
Triggers:
  - Type: PUSH
    Branches:
      - main
  - Type: SCHEDULE
    Expression: "0 2 * * ? *"
    Branches:
      - main
Compute:
  Type: EC2
  Fleet: Linux.x86-64.Large
Actions:
  build:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
      Variables:
        - Name: region
        - Name: bucketPrefix
        - Name: guidanceVersion
        - Name: DomainName
        - Name: UserProfileName
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: export REGION=$region
        - Run: export BUCKET_PREFIX=$bucketPrefix
        - Run: export BUCKET_NAME=$BUCKET_PREFIX-$REGION
        - Run: export GUIDANCE_NAME=guidance-for-intelligent-document-processing-on-aws
        - Run: export VERSION=$guidanceVersion
        - Run: git config --list
        - Run: git remote add upstream https://github.com/vprince1/aws-ai-intelligent-document-processing.git
        - Run: git fetch upstream
        - Run: git -c "user.name=Vijay Prince" -c "user.email=vjprince@amazon.com" merge upstream/main --allow-unrelated-histories
        - Run: git push
        - Run: echo ./.codecatalyst/create-bucket.sh $BUCKET_NAME $REGION
        - Run: ./.codecatalyst/create-bucket.sh $BUCKET_NAME $REGION
        - Run: aws s3 cp ./dist/idp-deploy.yaml
            s3://$BUCKET_NAME/$GUIDANCE_NAME/$VERSION/idp-deploy.yaml
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
    Environment:
      Name: prod_environment
  deploy:
    DependsOn:
      - build
    Identifier: aws/cfn-deploy@v1
    Configuration:
      parameter-overrides: DomainName=$DomainName,UserProfileName=$UserProfileName
      capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
      template: https://{{bucketPrefix}}-{{region}}.s3.{{region}}.amazonaws.com/guidance-for-intelligent-document-processing-on-aws/{{guidanceVersion}}/idp-deploy.yaml
      region: {{ region }}
      name: guidance-for-intelligent-document-processing-on-aws
    Environment:
      Name: prod_environment
