Name: secret-deployment
SchemaVersion: '1.0'
Triggers:
  - Type: PUSH
    Branches:
      - test-secret
  - Type: SCHEDULE
    Expression: "0 2 * * ? *"
    Branches:
      - test-secret
Compute:
  Type: EC2
  Fleet: Linux.x86-64.Large
Actions:
  build:
    Identifier: aws/build@v1
    Inputs:
      Sources:
        - WorkflowSource
    Outputs:
      AutoDiscoverReports:
        Enabled: false
        ReportNamePrefix: rpt
    Configuration:
      Steps:
        - Run: export REGION=${Secrets.region}
        - Run: export BUCKET_PREFIX=${Secrets.bucketPrefix}
        - Run: export BUCKET_NAME=$BUCKET_PREFIX-$REGION
        - Run: export GUIDANCE_NAME=guidance-for-intelligent-document-processing-on-aws
        - Run: export VERSION=${Secrets.guidanceVersion}
        - Run:
            echo aws s3api create-bucket --bucket $BUCKET_NAME  --region $REGION
            --create-bucket-configuration LocationConstraint=$REGION
        - Run:
            aws s3api create-bucket --bucket $BUCKET_NAME  --region $REGION
            --create-bucket-configuration LocationConstraint=$REGION
        - Run: aws s3 cp ./dist/idp-deploy.yaml
            s3://$BUCKET_NAME/$GUIDANCE_NAME/$VERSION/idp-deploy.yaml
      Container:
        Registry: CODECATALYST
        Image: CodeCatalystLinux_x86_64:2024_03
    Environment:
      Name: secret_prod_environment
  deploy:
    DependsOn:
      - build
    Identifier: aws/cfn-deploy@v1
    Configuration:
      parameter-overrides: DomainName=${Secrets.DomainName},UserProfileName=${Secrets.UserProfileName}
      capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
      template: https://$BUCKET_PREFIX-$REGION.s3.$REGION.amazonaws.com/guidance-for-intelligent-document-processing-on-aws/$VERSION/idp-deploy.yaml
      region: $REGION
      name: guidance-for-intelligent-document-processing-on-aws
    Environment:
      Name: secret_prod_environment

